language: java
jdk: oraclejdk8

env:
  global:
  - secure: "RVZHxtqjWaA1eXTCnt7Ia6qvJDxhvaEVEdXOfesPFyQnwq+t0vRjRaB8wogaWp7fFlp2d9hJFErb0TjmVRYvQVzfEh5R9YWrtlI8yvWFXv7qCmuSulpPTyBDxerJto7PIg15CDXSU15rTDkdH9ybZjnQY5K5h7ap+MjVAsD+WOoeJ6ndzEJJlA4vOp0dvx1l63ZG6i9oyzdmcWkioKESWhkmadvyXtn6H0+HJcTSq+5Drwj9QdLoZF+kFfl+eWkdDI52UwVYmvHGVxYIfSKwP7+KXWZyudfB1E1vKKytkej9XZy1dLZrW/ALdw6rqBnUzgsuzTX0SeyQpFjNoJreT1azWd6q8n3skJLbMKZP2ZUZdr9/oDxDU+kWWJk9LyGYgLBlg9i/kYsn3qbDVBxZEix4MVWSiS+NLT0EihWWSQ9XmYAIt9FVX8EnCVkUY7kloglUDzNFnFjw9LOXljZh75/03Rs1m/rQdsZcivYTLYJFTwmOvCytYsbvqwpyvCzWkkLbS/DA3NMMXuaRJQeA5HTIfhD7POIpcgyxoxKMEc6cJSYnIrmc5hR84zNiEHVKtltPuvX8RBqU9DNGfScH4i27jxCxBnoPOE5m6Zj25+cxSAVYnVbi3wWEyxlLxdusurxpqV36i84b69lZV8ZY2Wood/T7iVV6Xx95teREtlo="
  - secure: "fg4LgKxuURXoomd9d2S4cjI7C1nLT+FZPmvjrktVffm7DiV5pI1UFnuiGozhWRcyWWE0S3fso8Nm3V590xnc4jWkIKwaJnokwiDF2pzDKGhxhSbvltjGA/fNztIjX8A/PJHo0Ln5fAJj+TNVP9pmidQXbpe52ukrj0SLLiOzDIv3/iI41PZt00ApqFF0a8ne8M6Z09YLafeKRIprvCU/G6JDW9nQchxtbAQbw5Q1zlQ9+KhalVFKGKk2tN0qeT/RqY4oVP4ujrFqAxhq/typBtn4fSh5KZpJ3ufWnjiRUiisa8W0wzrPdSq2Z6qR6YAIsVcroEMsk3lcYfpbPooWY5ChIW0znzdMSnXP5FNNaw3AlnQgFSnLSGxNDRazvgcPH6A7z/N5/vkON5uHiWF9UqktlF6HygdkIez3W7fECvod7qF4mKmWHWpnc5WOji+s53cLmqsKdxnpCKPcRc49TKy0C0oekbYth0ccLWkHr+8jnkbyubfZ1G/bVSEsGyW8jMrLXwpydY+96zKVbHjs+/go2o7YdpD5fTq4f10YAr+iFSZ8lFBl3YhHYUAWsmB5sWeeGh1061qKNgeWXmEmaS0WTHRWKdoA9dP2ZCsYl4Cn0PQehh+syvRwje8xPe5LpH+yAofuTO2lzQkiKobmS3jtczZB/iFUWsEImT/mwzQ="
  - secure: "J0akqtQ8+VXMwQK9ZksPt+IZ7cr18TsB9mmbxDGXP+Ju+wdqhEfyb/3AFYwlh9Q6IjEMSr07gTsX0ayBsqoq2KW79lJeb3i/T45gYpdaXm42wHtD49PU3wKOlWvMbuDfx6AddkA6Y3T9i6TpfOo/NbJ08MfGBlZ9JhLhtwf4UA390fObeTeaPDlelYi783ZeH3YJKKglAR4BsXvT9Qaiv3w5B3cuEv0DYKxtWa8iNfVp0EhaKZb+zVvaRtLLIdOx/h6+t3onzLDh5tOdbX51b8YQ6k4LgV0mrt9zkW9StcHmGUNjaL8R7IGExgXuuQNUwyUQ8C1dtKFLm8ZJWqYjBSV+xNg+y5YPOs75EE2Ub/6Pu4wnWh9fFU8LfOcYyoTGT5ejDzPiPoKf+TMd5XiSaRG4HQAEvWUeaFPjZ4Zolvovc1a4Fdclu/KGGj+F7r4/X/vW974GA6MkcHJk0BAqjwvyqOEGcMI3Xy0uoylqpo0izzz+oma5j8SxOwaj0j56nUQI+WB/LoBljWcl3taUjrqfCvggC3dgIY7zNebyiPR28h3EryIZyDMpbBTZ99Y5qQufK+xHQ6YomPyTvIJwsVv8Fr4zwULOfWXDGikDF0VehO5a/k0+nMrY6eXxlP98mxglWTvZCvQYlJ3uD0sd5XVppacsSKiILEW5Bypob04="
  - secure: "ETcUUe1jwlTMXf3p7x1ycuIfZpLqP66SJEZzzYuyl8FQuOUo3W8k98uvEQUGNETqK279ncpD3LvBPZjo9wa246gXivXeIVqvPLu1/DsVId+2/GNTkC2cpgYjKsvB5lWsFXat71RlVvCv4apBnLsvLC0Cb4HfEWt7nzmWoMUONIkjRvvPSrbcnNUYEtboPTbA/ey0H7LblGAE+5E/dcrFU+G2X4DUwfqYKKCWUpWgQLr8q2mE4FvQkNmabFUlyUAYhG2iYWbarzUem30/nw8C0l5LRsO+mJkNGeG/VpAogNVhO9YQVEyJ0S+z70wr1Y2Py6tU+AgfCJei1qG0WSgjw8IoFi+3NSMRsoCd9IzjeqbU67ARNpd/Kp8tU68zJwoOf/Y1tSUA1jZud7dqJ9TJKzodJ4FPB/l78fXG5JoNfFfQ2D3iJGOmcaDY7trfPBPGATmOA2kYTFzTAYYh8n8rX3/SZMBpidC5WTIsh4cX9t8B+cb+bdv5jZtTUEs6fIxZjxWkVk9fJdbPlioJs+Y3Vi59JAbC3rzkL+hsqLbAdGQ2W7ggkeEGNZKepvRXvZhNPOWDB0yCyJv+M9KiwuwVgCT8fR4w8ZpRANbXVdLyaFPXB7fBCGffeaqLX6uZtgROxfkES0E49kj8pDNcQQc8Q+s19M6UXFCC+1wrwC9a3co="
  - COMMIT=${TRAVIS_COMMIT::7}

addons:
  sonarcloud:
    organization: "szotaa-github"
    token:
      secure: "cVVeXQGm8JkSbAbrSc77ZwG5+hQd9d0wzUkGkNqxxzKJMwTSdSHPhB1hR1LGaYcXsBYWLFwMzB/sHdyUH51TUvC5CTj90rogRp2S+3f0nozaqJEwM85+w/s1pTiKlf+6qnnGeFg/SGAFIV9VVKNTCmEznRSHftOtTm+ePopYDxA/Lei8uStIkL4XflaBiD+wfKYU/SK/A0/F4iVPu4UB7hChPAX+EHBdyBreKjiY4P/vrBy7MtVpEpmioaVVUFdGAB+u9JvETZwxi+riBTG99zR7plouJbudbsUkypTafyCgtgq/N5VHh1SlfDcdOpn4q8uIw9XErqUToJu2QW58IQxs1OlKnBfAQ6C52bGiEV8HctEbOs3Wfm3+qT3K0skvHMl2xoEXSJlOyP+nGXAlDd3O3t8FC7dWbIJJMAdUmHmSKP4HTsPqw21m1y/iQ6/8tzPDMDjU2QjitY8W6yH9oGOuJdbLOSwzCIdGkQFi18q2ekjdp2UFpRuNPZN941uiblsmGQJuoRF2iM77E1OOLVm9t8vkBsDlVXdIPtjdGmN+UuGbDnPjGJF50M9RdzLHe5361Xu0leMU9yurN1Zc4PwdT2fYBJQKoekLym7FpDQ87gIBlsW0tmE+ucRwbmG+oGAQGqiyM8gseoDlwArAYFj6fypDwFUp3YnJ/bYajio="


sudo: required

services:
  - docker

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- export IMAGE_NAME=szotaa/travis-demo
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: freelancerkit

script:
- ./mvnw clean install -B
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar