language: java
jdk: oraclejdk8

env:
  global:
  - secure: "RVZHxtqjWaA1eXTCnt7Ia6qvJDxhvaEVEdXOfesPFyQnwq+t0vRjRaB8wogaWp7fFlp2d9hJFErb0TjmVRYvQVzfEh5R9YWrtlI8yvWFXv7qCmuSulpPTyBDxerJto7PIg15CDXSU15rTDkdH9ybZjnQY5K5h7ap+MjVAsD+WOoeJ6ndzEJJlA4vOp0dvx1l63ZG6i9oyzdmcWkioKESWhkmadvyXtn6H0+HJcTSq+5Drwj9QdLoZF+kFfl+eWkdDI52UwVYmvHGVxYIfSKwP7+KXWZyudfB1E1vKKytkej9XZy1dLZrW/ALdw6rqBnUzgsuzTX0SeyQpFjNoJreT1azWd6q8n3skJLbMKZP2ZUZdr9/oDxDU+kWWJk9LyGYgLBlg9i/kYsn3qbDVBxZEix4MVWSiS+NLT0EihWWSQ9XmYAIt9FVX8EnCVkUY7kloglUDzNFnFjw9LOXljZh75/03Rs1m/rQdsZcivYTLYJFTwmOvCytYsbvqwpyvCzWkkLbS/DA3NMMXuaRJQeA5HTIfhD7POIpcgyxoxKMEc6cJSYnIrmc5hR84zNiEHVKtltPuvX8RBqU9DNGfScH4i27jxCxBnoPOE5m6Zj25+cxSAVYnVbi3wWEyxlLxdusurxpqV36i84b69lZV8ZY2Wood/T7iVV6Xx95teREtlo="

addons:
  sonarcloud:
    organization: "szotaa"
    token:
      secure: $SONAR_TOKEN


script:
- ./mvnw clean install -B
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar